{{- if has "mongodb" .Values.apps }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.nombre }}
type: Opaque
stringData:
  mongo-root-username: "root"
  mongo-root-password: "changeme"
{{- end }}
