{{- if has "mysql" .Values.apps }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.nombre }}
type: Opaque
stringData:
  # In a real environment, this should probably be generated or more secure.
  mysql-root-password: "changeme"
{{- end }}
